### ISSUE TITLE
Updating comment data to include following columns

### ISSUE THREAD

**Issue by 15sora2** [UMM-CSci-3601-S17/digital-display-garden-iteration-3-dorfner#2]
- [ ] commonName
- [ ] cultivar
- [ ] bed location

**Comment by ferri082** [comment]
Need to fix db in order to export correct information. Adding comments and the interactions functions work with the new db functionality. The writing to an excel file does not work.

**Comment by ferri082** [comment]
Tests: successfulInputofComment() and failedInputOfComment() need to be fixed due to new db setup
